### ISSUE TITLE
JMeter RestAPI - How to send json body as request along with an image(jpeg/jpg) file in JMeter

### ISSUE THREAD

**Issue by TariniMohanty** [spinning10/JMeterSoapSampler#11]
Hello All,

I am trying to send json body in JMeter (body data) for my RestAPI - PUT along with an attachment (jpeg/jpg) file. Every-time I get the response as "{"error":"Incorrect number of attachments."}".

I have the jpeg/jpg file which needs to be sent in Jmeter/bin folder.
 Body Data tab in JMeter-
{
    "message": {
        "viewers": [
            
        ],
        "attachments": [
            {
                "name": "googleImage.jpg",
                "mimeType": "image/jpg"
            }
        ],
        "messageBody": "Hello World! - Test Attachments",
        "subjectLine": "Test message - 0927T09:58",
        "messageID": "",
        "toAddress": "some reqd value"
    }
}
Header has-
Content-Type- application/json
Accept- application/json, image/jpeg
Also tried with- 
Accept-multipart/form-data 
Accept-multipart/mixed

**Comment by spinning10** [comment]
Hello, the Sampler I made is for SOAP. I think you need to use just standard http sampler and if I remember well there was attachment capability. Please further let know if it was a solution or not.
