### ISSUE TITLE
The plugin not work with standart HTTP Auth Manager

### ISSUE THREAD

**Issue by Tohtig** [spinning10/JMeterSoapSampler#5]
Hello!
We can see that in View Result Tree. Our SOAP request sending without any header (Basic Auth). Maybe it's becouse you inherited just AbstractSampler without HTTP family ecosystem.
I don't know how can added auth for sampler in this realisation. Can you help?

**Comment by spinning10** [comment]
Hi, I think last 2 pull requests whoch are already merged come handy with that issue. If you still experience it with the latest version pls let know here.
